// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Produto.Data;

#nullable disable

namespace Produto.Data.Migrations
{
    [DbContext(typeof(ProdutosContext))]
    [Migration("20250323223155_newseed")]
    partial class newseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Produto.Data.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0195c525-9a61-711c-8f23-fe5648bb690a"),
                            Descricao = "Descrição do Produto 1",
                            Estoque = 100,
                            Nome = "Produto 1",
                            Valor = 10.00m
                        },
                        new
                        {
                            Id = new Guid("0195c525-9a61-711c-8f24-03f9b0e3cd25"),
                            Descricao = "Descrição do Produto 2",
                            Estoque = 200,
                            Nome = "Produto 2",
                            Valor = 20.00m
                        },
                        new
                        {
                            Id = new Guid("0195c525-9a61-711c-8f24-0592096c4b61"),
                            Descricao = "Descrição do Produto 3",
                            Estoque = 300,
                            Nome = "Produto 3",
                            Valor = 30.00m
                        },
                        new
                        {
                            Id = new Guid("0195c525-9a61-711c-8f24-0b3d685cc7d6"),
                            Descricao = "Descrição do Produto 4",
                            Estoque = 400,
                            Nome = "Produto 4",
                            Valor = 40.00m
                        },
                        new
                        {
                            Id = new Guid("0195c525-9a61-711c-8f24-0c11233469cf"),
                            Descricao = "Descrição do Produto 5",
                            Estoque = 500,
                            Nome = "Produto 5",
                            Valor = 50.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
